FROM node:18-alpine

WORKDIR /app

# Install dependencies first
COPY package*.json ./
RUN npm install


COPY . .
# No need to copy source code - will be mounted
EXPOSE 8080

# CMD ["npm", "run", "dev"]
# CMD ["npm", "run", "dev:frontend"]
CMD ["node", "/app/frontend/src/index.js"]