FROM node:18-alpine

WORKDIR /app

# Install dependencies first (leverages Docker cache)
COPY package.json ./
RUN npm install

COPY . .

# No need to copy source code - will be mounted
EXPOSE 3000

# CMD ["npm", "run", "dev"]
# CMD ["npm", "run", "dev:backend"]
CMD ["node", "/app/backend/src/index.js"]